// frontend is called by the backend
interface Frontend {
    // callback to receive raw chordata frame
    oneway void chordata(in sequence<octet> data);

    // callbacks to receive face data
    // names for the entries in faceLandmarks() blendshapes sequence

    // send at the beginning or whenever that list of names changes
    oneway void faceBlendshapeNames(in sequence<string> faceBlendshapeNames);
    oneway void faceLandmarks(
        in sequence<float> landmarks,
        in sequence<float> blendshapes,
        in sequence<float> transform,
        in unsigned long long timestamp_ms);

    oneway void poseLandmarks(
        in sequence<float> landmarks,
        in unsigned long long timestamp_ms);

    // temporary hack
    oneway void frame(in unsigned long frame);
};

interface VideoCamera {
    readonly attribute string id;
    attribute string name;
    readonly attribute string features;
};

interface MediaPipeTask {
    readonly attribute string name;
};

struct VideoSize {
    unsigned short fps;
    unsigned long frames;
};

interface Recorder {
    VideoSize open(in string filename);
    void close();
    void record();
    void play();
    void stop();
    void pause();
    void seek(in unsigned long frame);
};

// backend is called by the frontend
interface Backend {
    // called by the frontend to register itself to receive data
    void setFrontend(in Frontend frontend);

    readonly attribute Recorder recorder;

    sequence<VideoCamera> getVideoCameras();
    attribute VideoCamera camera;

    sequence<MediaPipeTask> getMediaPipeTasks();
    attribute MediaPipeTask mediaPipeTask;
};
